version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: name.remal.check-dependency-updates
    versions:
    - "> 1.2.2"
